version: '3.3'

services:
  db:
    image: ${DB_TYPE}:latest
    container_name: nestjs_angular_talk_db
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis
    container_name: nestjs_angular_talk_redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'



#  db:
#    image: container-registry.oracle.com/database/enterprise:latest
#    container_name: nap_db
#    ports:
#      - "${DB_PORT}:1521"
#      - "${ORACLE_EM_PORT}:5500"
#    environment:
#      - ORACLE_SID=${DB_USER}
#      - ORACLE_PDB=${DB_NAME}
#      - ORACLE_PWD=${DB_PASSWORD}
#      - ORACLE_CHARACTERSET=AL32UTF8
